# Centralized management of versions for scalability and maintenance
springBootVersion = 3.3.5
springDependencyManagementVersion = 1.1.6
sonarqubeVersion = 6.0.1.5171
logcaptorVersion = 2.9.3
dotenvJavaVersion = 3.0.2
jjwtVersion = 0.9.1
postgresqlVersion = 42.7.2
checkstyleVersion = 10.20.0
jacocoVersion = 0.8.12

# Allow task parallelism
org.gradle.parallel=true