spring.application.name=users-management-system
spring.profiles.active=dev

# Server Configuration
server.port=${PORT:8080}

# Error settings
server.error.include-message=always
server.error.include-binding-errors=always

# Read environment variables from file
spring.config.import=optional:file:.env[.properties]

# PostgreSQL Database
# For development, the database information is saved in a '.env' file.
# In Production, using Docker secrets, HashiCorp Vault, or Spring Cloud Config
# would be the better policy.
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging settings
logging.level.io.github.ajmiller611.usermanagement=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Exception Settings
spring.jackson.deserialization.fail-on-unknown-properties=true