spring.application.name=users-management-system

# Error settings
server.error.include-message=always
server.error.include-binding-errors=always

# Read environment variables from file
spring.config.import=optional:file:.env[.properties]

# Configuration for PostgreSQL Database used during integration testing.
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/test_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

# Disable Spring Cloud Config for testing
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Logging settings
logging.level.root=DEBUG
logging.level.io.github.ajmiller611.usermanagement=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.hibernate.SQL=DEBUG